var dir_7802e3637595e087f277d79ec8a6f062 =
[
    [ "autogenerated", "dir_439ac4876c39108ff591ed52489d8c53.html", "dir_439ac4876c39108ff591ed52489d8c53" ],
    [ "b3BulletFile.h", "b3_bullet_file_8h.html", [
      [ "b3BulletFile", "classb_parse_1_1b3_bullet_file.html", "classb_parse_1_1b3_bullet_file" ]
    ] ],
    [ "b3Chunk.h", "b3_chunk_8h.html", "b3_chunk_8h" ],
    [ "b3Common.h", "b3_common_8h.html", "b3_common_8h" ],
    [ "b3Defines.h", "b3_defines_8h.html", "b3_defines_8h" ],
    [ "b3DNA.h", "b3_d_n_a_8h.html", [
      [ "bNameInfo", "structb_parse_1_1b_name_info.html", "structb_parse_1_1b_name_info" ],
      [ "bDNA", "classb_parse_1_1b_d_n_a.html", "classb_parse_1_1b_d_n_a" ]
    ] ],
    [ "b3File.h", "b3_file_8h.html", "b3_file_8h" ],
    [ "b3Serializer.h", "b3_serializer_8h.html", "b3_serializer_8h" ]
];