var hierarchy =
[
    [ "Affordance", "struct_affordance.html", null ],
    [ "AModel", "class_a_model.html", null ],
    [ "Animation", "class_animation.html", null ],
    [ "AnimationManager", "class_animation_manager.html", null ],
    [ "AScript", "class_a_script.html", null ],
    [ "Bone", "class_bone.html", null ],
    [ "AModel::BoneInfo", "struct_a_model_1_1_bone_info.html", null ],
    [ "btIDebugDraw", null, [
      [ "GraphicsEngine", "class_graphics_engine.html", null ]
    ] ],
    [ "Camera", "struct_camera.html", null ],
    [ "CComponent", "class_c_component.html", [
      [ "CAffordanceManager", "class_c_affordance_manager.html", null ],
      [ "CAgent", "class_c_agent.html", null ],
      [ "CAnimator", "class_c_animator.html", null ],
      [ "CCamera", "class_c_camera.html", null ],
      [ "CCharacter", "class_c_character.html", null ],
      [ "CCollider", "class_c_collider.html", null ],
      [ "CDirectionalLight", "class_c_directional_light.html", null ],
      [ "CNavMesh", "class_c_nav_mesh.html", null ],
      [ "CPointLight", "class_c_point_light.html", null ],
      [ "CRigidBody", "class_c_rigid_body.html", null ],
      [ "CScript", "class_c_script.html", null ],
      [ "CSound", "class_c_sound.html", null ],
      [ "CStaticMesh", "class_c_static_mesh.html", null ]
    ] ],
    [ "Manifold::ContactPoint", "class_manifold_1_1_contact_point.html", null ],
    [ "btCollisionWorld::ContactResultCallback", null, [
      [ "CollisionManager", "class_collision_manager.html", null ]
    ] ],
    [ "Engine", "class_engine.html", null ],
    [ "ExampleAppConsole", "struct_example_app_console.html", null ],
    [ "ExampleAppDocuments", "struct_example_app_documents.html", null ],
    [ "ExampleAppLog", "struct_example_app_log.html", null ],
    [ "GameAssetFactory", "class_game_asset_factory.html", null ],
    [ "GameObject", "class_game_object.html", null ],
    [ "GameObjectFactory", "class_game_object_factory.html", null ],
    [ "GL3WProcs", "union_g_l3_w_procs.html", null ],
    [ "gladGLversionStruct", "structglad_g_lversion_struct.html", null ],
    [ "Graph", "struct_graph.html", null ],
    [ "GridLocation", "struct_grid_location.html", null ],
    [ "ImBitArray< BITCOUNT >", "struct_im_bit_array.html", null ],
    [ "ImBitVector", "struct_im_bit_vector.html", null ],
    [ "ImChunkStream< T >", "struct_im_chunk_stream.html", null ],
    [ "ImChunkStream< ImGuiTableSettings >", "struct_im_chunk_stream.html", null ],
    [ "ImChunkStream< ImGuiWindowSettings >", "struct_im_chunk_stream.html", null ],
    [ "ImColor", "struct_im_color.html", null ],
    [ "ImDrawChannel", "struct_im_draw_channel.html", null ],
    [ "ImDrawCmd", "struct_im_draw_cmd.html", null ],
    [ "ImDrawCmdHeader", "struct_im_draw_cmd_header.html", null ],
    [ "ImDrawData", "struct_im_draw_data.html", null ],
    [ "ImDrawDataBuilder", "struct_im_draw_data_builder.html", null ],
    [ "ImDrawList", "struct_im_draw_list.html", null ],
    [ "ImDrawListSharedData", "struct_im_draw_list_shared_data.html", null ],
    [ "ImDrawListSplitter", "struct_im_draw_list_splitter.html", null ],
    [ "ImDrawVert", "struct_im_draw_vert.html", null ],
    [ "ImFont", "struct_im_font.html", null ],
    [ "ImFontAtlas", "struct_im_font_atlas.html", null ],
    [ "ImFontAtlasCustomRect", "struct_im_font_atlas_custom_rect.html", null ],
    [ "ImFontBuildDstData", "struct_im_font_build_dst_data.html", null ],
    [ "ImFontBuilderIO", "struct_im_font_builder_i_o.html", null ],
    [ "ImFontBuildSrcData", "struct_im_font_build_src_data.html", null ],
    [ "ImFontConfig", "struct_im_font_config.html", null ],
    [ "ImFontGlyph", "struct_im_font_glyph.html", null ],
    [ "ImFontGlyphRangesBuilder", "struct_im_font_glyph_ranges_builder.html", null ],
    [ "ImGui_ImplOpenGL3_Data", "struct_im_gui___impl_open_g_l3___data.html", null ],
    [ "ImGui_ImplSDL2_Data", "struct_im_gui___impl_s_d_l2___data.html", null ],
    [ "ImGuiColorMod", "struct_im_gui_color_mod.html", null ],
    [ "ImGuiComboPreviewData", "struct_im_gui_combo_preview_data.html", null ],
    [ "ImGuiContext", "struct_im_gui_context.html", null ],
    [ "ImGuiContextHook", "struct_im_gui_context_hook.html", null ],
    [ "ImGuiDataTypeInfo", "struct_im_gui_data_type_info.html", null ],
    [ "ImGuiDataTypeTempStorage", "struct_im_gui_data_type_temp_storage.html", null ],
    [ "ImGuiGroupData", "struct_im_gui_group_data.html", null ],
    [ "ImGuiInputTextCallbackData", "struct_im_gui_input_text_callback_data.html", null ],
    [ "ImGuiInputTextState", "struct_im_gui_input_text_state.html", null ],
    [ "ImGuiIO", "struct_im_gui_i_o.html", null ],
    [ "ImGuiLastItemData", "struct_im_gui_last_item_data.html", null ],
    [ "ImGuiListClipper", "struct_im_gui_list_clipper.html", null ],
    [ "ImGuiMenuColumns", "struct_im_gui_menu_columns.html", null ],
    [ "ImGuiMetricsConfig", "struct_im_gui_metrics_config.html", null ],
    [ "ImGuiNavItemData", "struct_im_gui_nav_item_data.html", null ],
    [ "ImGuiNextItemData", "struct_im_gui_next_item_data.html", null ],
    [ "ImGuiNextWindowData", "struct_im_gui_next_window_data.html", null ],
    [ "ImGuiOldColumnData", "struct_im_gui_old_column_data.html", null ],
    [ "ImGuiOldColumns", "struct_im_gui_old_columns.html", null ],
    [ "ImGuiOnceUponAFrame", "struct_im_gui_once_upon_a_frame.html", null ],
    [ "ImGuiPayload", "struct_im_gui_payload.html", null ],
    [ "ImGuiPlotArrayGetterData", "struct_im_gui_plot_array_getter_data.html", null ],
    [ "ImGuiPopupData", "struct_im_gui_popup_data.html", null ],
    [ "ImGuiPtrOrIndex", "struct_im_gui_ptr_or_index.html", null ],
    [ "ImGuiResizeBorderDef", "struct_im_gui_resize_border_def.html", null ],
    [ "ImGuiResizeGripDef", "struct_im_gui_resize_grip_def.html", null ],
    [ "ImGuiSettingsHandler", "struct_im_gui_settings_handler.html", null ],
    [ "ImGuiShrinkWidthItem", "struct_im_gui_shrink_width_item.html", null ],
    [ "ImGuiSizeCallbackData", "struct_im_gui_size_callback_data.html", null ],
    [ "ImGuiStackSizes", "struct_im_gui_stack_sizes.html", null ],
    [ "ImGuiStorage", "struct_im_gui_storage.html", null ],
    [ "ImGuiStorage::ImGuiStoragePair", "struct_im_gui_storage_1_1_im_gui_storage_pair.html", null ],
    [ "ImGuiStyle", "struct_im_gui_style.html", null ],
    [ "ImGuiStyleMod", "struct_im_gui_style_mod.html", null ],
    [ "ImGuiStyleVarInfo", "struct_im_gui_style_var_info.html", null ],
    [ "ImGuiTabBar", "struct_im_gui_tab_bar.html", null ],
    [ "ImGuiTabBarSection", "struct_im_gui_tab_bar_section.html", null ],
    [ "ImGuiTabItem", "struct_im_gui_tab_item.html", null ],
    [ "ImGuiTable", "struct_im_gui_table.html", null ],
    [ "ImGuiTableCellData", "struct_im_gui_table_cell_data.html", null ],
    [ "ImGuiTableColumn", "struct_im_gui_table_column.html", null ],
    [ "ImGuiTableColumnSettings", "struct_im_gui_table_column_settings.html", null ],
    [ "ImGuiTableColumnSortSpecs", "struct_im_gui_table_column_sort_specs.html", null ],
    [ "ImGuiTableSettings", "struct_im_gui_table_settings.html", null ],
    [ "ImGuiTableSortSpecs", "struct_im_gui_table_sort_specs.html", null ],
    [ "ImGuiTableTempData", "struct_im_gui_table_temp_data.html", null ],
    [ "ImGuiTextBuffer", "struct_im_gui_text_buffer.html", null ],
    [ "ImGuiTextFilter", "struct_im_gui_text_filter.html", null ],
    [ "ImGuiTextFilter::ImGuiTextRange", "struct_im_gui_text_filter_1_1_im_gui_text_range.html", null ],
    [ "ImGuiViewport", "struct_im_gui_viewport.html", [
      [ "ImGuiViewportP", "struct_im_gui_viewport_p.html", null ]
    ] ],
    [ "ImGuiWindow", "struct_im_gui_window.html", null ],
    [ "ImGuiWindowSettings", "struct_im_gui_window_settings.html", null ],
    [ "ImGuiWindowStackData", "struct_im_gui_window_stack_data.html", null ],
    [ "ImGuiWindowTempData", "struct_im_gui_window_temp_data.html", null ],
    [ "ImNewWrapper", "struct_im_new_wrapper.html", null ],
    [ "ImPool< T >", "struct_im_pool.html", null ],
    [ "ImPool< ImGuiTabBar >", "struct_im_pool.html", null ],
    [ "ImPool< ImGuiTable >", "struct_im_pool.html", null ],
    [ "ImRect", "struct_im_rect.html", null ],
    [ "ImSpan< T >", "struct_im_span.html", null ],
    [ "ImSpan< ImGuiTableCellData >", "struct_im_span.html", null ],
    [ "ImSpan< ImGuiTableColumn >", "struct_im_span.html", null ],
    [ "ImSpan< ImGuiTableColumnIdx >", "struct_im_span.html", null ],
    [ "ImSpanAllocator< CHUNKS >", "struct_im_span_allocator.html", null ],
    [ "ImVec1", "struct_im_vec1.html", null ],
    [ "ImVec2", "struct_im_vec2.html", null ],
    [ "ImVec2ih", "struct_im_vec2ih.html", null ],
    [ "ImVec4", "struct_im_vec4.html", null ],
    [ "ImVector< T >", "struct_im_vector.html", null ],
    [ "ImVector< char * >", "struct_im_vector.html", null ],
    [ "ImVector< char >", "struct_im_vector.html", null ],
    [ "ImVector< const char * >", "struct_im_vector.html", null ],
    [ "ImVector< float >", "struct_im_vector.html", null ],
    [ "ImVector< ImDrawChannel >", "struct_im_vector.html", null ],
    [ "ImVector< ImDrawCmd >", "struct_im_vector.html", null ],
    [ "ImVector< ImDrawIdx >", "struct_im_vector.html", null ],
    [ "ImVector< ImDrawList * >", "struct_im_vector.html", null ],
    [ "ImVector< ImDrawVert >", "struct_im_vector.html", null ],
    [ "ImVector< ImFont * >", "struct_im_vector.html", null ],
    [ "ImVector< ImFontAtlasCustomRect >", "struct_im_vector.html", null ],
    [ "ImVector< ImFontConfig >", "struct_im_vector.html", null ],
    [ "ImVector< ImFontGlyph >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiColorMod >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiContextHook >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiGroupData >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiID >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiItemFlags >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiOldColumnData >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiOldColumns >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiPopupData >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiPtrOrIndex >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiSettingsHandler >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiShrinkWidthItem >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiStorage::ImGuiStoragePair >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiStyleMod >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiTabItem >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiTableColumnSortSpecs >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiTableTempData >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiTextFilter::ImGuiTextRange >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiViewportP * >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiWindow * >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiWindowStackData >", "struct_im_vector.html", null ],
    [ "ImVector< ImTextureID >", "struct_im_vector.html", null ],
    [ "ImVector< ImU32 >", "struct_im_vector.html", null ],
    [ "ImVector< ImVec2 >", "struct_im_vector.html", null ],
    [ "ImVector< ImVec4 >", "struct_im_vector.html", null ],
    [ "ImVector< ImWchar >", "struct_im_vector.html", null ],
    [ "ImVector< int >", "struct_im_vector.html", null ],
    [ "ImVector< MyDocument >", "struct_im_vector.html", null ],
    [ "ImVector< unsigned char >", "struct_im_vector.html", null ],
    [ "InputManager", "class_input_manager.html", null ],
    [ "Key", "struct_key.html", null ],
    [ "KeyPosition", "struct_key_position.html", null ],
    [ "KeyRotation", "struct_key_rotation.html", null ],
    [ "KeyScale", "struct_key_scale.html", null ],
    [ "LevelEditor", "class_level_editor.html", null ],
    [ "LevelLoader", "class_level_loader.html", null ],
    [ "LightManager", "class_light_manager.html", null ],
    [ "Manifold", "class_manifold.html", null ],
    [ "Matrix3f", "class_matrix3f.html", null ],
    [ "Matrix4f", "class_matrix4f.html", null ],
    [ "Mesh", "class_mesh.html", null ],
    [ "MouseButton", "struct_mouse_button.html", null ],
    [ "MyDocument", "struct_my_document.html", null ],
    [ "MyTime", "class_my_time.html", null ],
    [ "NavNode", "class_nav_node.html", null ],
    [ "Animation::NodeData", "struct_animation_1_1_node_data.html", null ],
    [ "PhysicsManager", "class_physics_manager.html", null ],
    [ "PriorityQueue< T, priority_t >", "struct_priority_queue.html", null ],
    [ "Quaternion", "class_quaternion.html", null ],
    [ "btCollisionWorld::RayResultCallback", null, [
      [ "CollisionManager", "class_collision_manager.html", null ]
    ] ],
    [ "ScriptingEngine", "class_scripting_engine.html", null ],
    [ "Shader", "class_shader.html", null ],
    [ "ShadowMapper", "class_shadow_mapper.html", null ],
    [ "SkyBox", "class_sky_box.html", null ],
    [ "SoundManager", "class_sound_manager.html", null ],
    [ "STB_TexteditState", "struct_s_t_b___textedit_state.html", null ],
    [ "stbrp_context", "structstbrp__context.html", null ],
    [ "stbrp_node", "structstbrp__node.html", null ],
    [ "stbrp_rect", "structstbrp__rect.html", null ],
    [ "StbTexteditRow", "struct_stb_textedit_row.html", null ],
    [ "stbtt__bitmap", "structstbtt____bitmap.html", null ],
    [ "stbtt__buf", "structstbtt____buf.html", null ],
    [ "stbtt_aligned_quad", "structstbtt__aligned__quad.html", null ],
    [ "stbtt_bakedchar", "structstbtt__bakedchar.html", null ],
    [ "stbtt_fontinfo", "structstbtt__fontinfo.html", null ],
    [ "stbtt_pack_context", "structstbtt__pack__context.html", null ],
    [ "stbtt_pack_range", "structstbtt__pack__range.html", null ],
    [ "stbtt_packedchar", "structstbtt__packedchar.html", null ],
    [ "stbtt_vertex", "structstbtt__vertex.html", null ],
    [ "StbUndoRecord", "struct_stb_undo_record.html", null ],
    [ "StbUndoState", "struct_stb_undo_state.html", null ],
    [ "Texture", "struct_texture.html", null ],
    [ "Transform", "class_transform.html", null ],
    [ "Vector2f", "class_vector2f.html", null ],
    [ "Vector3f", "class_vector3f.html", null ],
    [ "Vertex", "struct_vertex.html", null ]
];